// components/Breadcrumbs/index.tsx
import ChevronRight from '../Icons/ChevronRight';
import Text from '../Text';

import style from './style.module.scss';

type BreadcrumbsProps = {
  path: Array<{ title: string; href: string }>;
};

export default function Breadcrumbs(props: BreadcrumbsProps) {
  return (
    <div className={style.breadcrumbs}>
      {props.path.map((part, index) => (
        <div
          key={part.href}
          style={{ color: index < props.path.length - 1 ? 'var(--text-body)' : undefined }}
        >
          <Text as="a" href={part.href}>
            {part.title}
          </Text>
          {index < props.path.length - 1 && <ChevronRight width={12} height={12} />}
        </div>
      ))}
    </div>
  );
}

// src/lib/components/Breadcrumbs.svelte
<script lang="ts">
	import ChevronRight from "$lib/icons/ChevronRight.svelte";
	import type { BreadcrumbPart } from "src/global";

	export let path: BreadcrumbPart[];
</script>

<div class="mb-10 text-navigation text-general flex gap-2">
	{#each path as part, index}
		<div
			class="flex gap-2 items-center"
			class:text-body={index < path.length - 1}
		>
			<a href={part.href}>{part.title}</a>
			{#if index < path.length - 1}
				<ChevronRight width={12} height={12} />
			{/if}
		</div>
	{/each}
</div>
